# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: b87731e
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-latest
active: true
github_repo_name: copier-python
project_description: Copier template for Python projects.
project_email: blake.naccarato@gmail.com
project_name: copier_python
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
project_version: 0.0.0
python_version: '3.11'
year_of_project_creation: 2022
