stages:
  example:
    cmd: pwsh -Command "./j.ps1 copier-pipeline-pipeline stage example"
    deps:
    - packages/_pipeline/src/copier_pipeline/stages/example
    - docs/notebooks/example.ipynb
    - data/example
    outs:
    - data/example_out:
        persist: true
    params:
    - stage
