"""Short description of the tests for your project.

Long description of the `pytest` tests for your project.

This was automatically generated by the Copier template. It will only be created again
if a README.md doesn't exist.
"""

import dummy

def test_example():
    """Short description of this test.

    Long description of this test.

    This is an example test generated by the Copier template. As you write code in
    `src/{{ project_name }}`, you should also write tests. This one is a toy example
    that checks whether your import is the same as the name you supplied to Copier.
    """

    assert dummy.__name__ == "dummy"
