"""Short description of your project.

Long description of your project.

This was automatically generated by the Copier template. It will only be created again
if this file is deleted.
"""

__version__ = "0.0.0"
